apiVersion: apps/v1
kind: Deployment
metadata:
  name: axz-gateway
  namespace: axz-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: axz-gateway
  template:
    metadata:
      labels:
        app: axz-gateway
    spec:
      containers:
      - name: gateway
        image: axz/gateway:latest
        ports:
        - containerPort: 8000
        env:
        - name: CONTROL_PLANE_URL
          value: "http://axz-control-plane:8080" 