apiVersion: v1
kind: Secret
metadata:
  name: axz-control-plane-secret
  namespace: axz-system
type: Opaque
data:
  # These are example values - replace in production
  database-password: YXh6MTIz
  vault-token: cm9vdA==
  rabbitmq-password: YXh6MTIz 